name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip python3-pip
          python3 -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-

      - name: Cache Buildozer local directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-local-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-local-

      - name: Accept Android SDK licenses
        run: |
          yes | buildozer android debug || true
          # Alternative method to accept licenses
          mkdir -p ~/.android
          echo 'count=0' > ~/.android/repositories.cfg
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/tools/bin

          # Accept any remaining licenses during build
          echo "y" | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OTPInterceptor-APK
          path: bin/*.apk
          retention-days: 30
